### ISSUE TITLE
path separators are os dependent

### ISSUE THREAD

**Issue by tkamm** [shekharchander/tube_dl#1]
Nice package! Tried under linux and I had to modify formats.py.

final_path = f'{path}\\{file_name}.{extension}'
to:
final_path = f'{path}' + os.path.sep + f'{file_name}.{extension}'

I'm sure there are other places that the separator should be fixed.

**Comment by shekharchander** [comment]
Thanks for your valuable feedback. I will update this asap. Please let me know if any other issues are there
