### ISSUE TITLE
Tube_dl library import isn't recognized!

### ISSUE THREAD

**Issue by EsdrasUday** [shekharchander/tube_dl#17]
Python version>> 3.10.5

Command used for installation: "pip install tube_dl".

The tube_dl library was installed, but at the time of import it is not recognized, I imported the same as the usage tutorial, but it is not found or recognized, the command: "from tube_dl import Youtube" I did a search for cmd with the command "pip3 list" and it really said that it was installed, but when looking for the folder in tube_dl on venv, it is not, please help me, I need this library a lot.

**Comment by shekharchander** [comment]
Hi @EsdrasUday Do you have any other file with name tube_dl.py by any chance?

**Comment by EsdrasUday** [comment]
> Hi @EsdrasUday Do you have any other file with name tube_dl.py by any chance?

I solved the problem, it was the vscode that was misconfigured
