### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Sekisback** [shekharchander/tube_dl#7]
according to your usage

from tube_dl import Youtube
yt = Youtube("https://youtube.com/watch?v=R2j46bHm6zw&list=RDAMVMd4HYhxlsj5k")
yt.formats.first().download()

Error:
yt = Youtube("https://youtube.com/watch?v=R2j46bHm6zw&list=RDAMVMd4HYhxlsj5k")
  File "/usr/local/lib/python3.9/dist-packages/tube_dl/__main__.py", line 75, in __init__
    self.likes=re.findall(r"'label': '(.*?) likes'",str(i))[0].replace(',','')
IndexError: list index out of range

**Comment by shekharchander** [comment]
I will be fixing the scripts very soon. Working on making it fast and error free. Wait for a day or two
