### ISSUE TITLE
Key Error 'Runs'

### ISSUE THREAD

**Issue by RockoonTechnologies** [shekharchander/tube_dl#9]
Getting an Error when running the following:

Youtube("https://youtube.com/watch?v=R2j46bHm6zw&list=RDAMVMd4HYhxlsj5k").formats.filter_by(only_audio=True).first()

File "[myPath]\env\lib\site-packages\tube_dl\__main__.py", line 64, in __init__
    self.subscribers=extraDetails[1]['videoSecondaryInfoRenderer']["owner"]["videoOwnerRenderer"]["subscriberCountText"]["runs"][0]
KeyError: 'runs'

**Comment by shekharchander** [comment]
> Getting an Error when running the following:
> 
> Youtube("[https://youtube.com/watch?v=R2j46bHm6zw&list=RDAMVMd4HYhxlsj5k").formats.filter_by(only_audio=True).first(](https://youtube.com/watch?v=R2j46bHm6zw&list=RDAMVMd4HYhxlsj5k%22).formats.filter_by(only_audio=True).first())
> 
> File "[myPath]\env\lib\site-packages\tube_dl__main__.py", line 64, in **init**
> self.subscribers=extraDetails[1]['videoSecondaryInfoRenderer']["owner"]["videoOwnerRenderer"]["subscriberCountText"]["runs"][0]
> KeyError: 'runs'

It will be fixed soon

**Comment by RockoonTechnologies** [comment]
Ok cool, was curious if I was doing something wrong

**Comment by shekharchander** [comment]
Hi @RockoonTechnologies This issue was already fixed in #8. Please download the latest file from here : [tube_dl-5.0.4-py3-none-any.whl](https://github.com/shekharchander/tube_dl/blob/master/dist/tube_dl-5.0.4-py3-none-any.whl). I have not updated that file in Python PIP
